Repository codesuqad-team3-to-do-list/todo-max, pull requests merged in 2023-07, with the labels that each got.

#6 [FE] ThemeProvider designSystem 구현, 헤더 UI 구현
  fe/src/App.tsx
  fe/src/components/Header.tsx
  fe/src/components/Logo.tsx
  fe/src/components/Navbar.tsx
  fe/src/components/header/Header.tsx
  fe/src/components/header/Logo.tsx
  fe/src/components/header/Navbar.tsx
  fe/src/main.tsx
  fe/src/styles/boxShadow.ts
  fe/src/styles/colors.ts
  fe/src/styles/designSystem.ts
  fe/src/styles/fonts.ts
Labels: ✨ feature

#11 [BE] application.yml에서 Local용 RDS 연동 및 Jasypt 암호화 적용
  BE/app/build.gradle
  BE/app/src/main/java/com/todo/app/common/JasyptConfig.java
  BE/app/src/main/resources/application.properties
  BE/app/src/main/resources/application.yml
Labels: 🛠️ infra

#15 [FE] designSystem에 Color System 추가
  fe/src/styles/designSystem.ts
Labels: ✨ feature

#12 [BE] 메인 페이지(컬럼+카드)를 불러오는 기능 구현
  BE/app/src/main/java/com/todo/app/common/ApiResponse.java
  BE/app/src/main/java/com/todo/app/common/config/RedisConfig.java
  BE/app/src/main/java/com/todo/app/common/exception/GlobalExceptionHandler.java
  BE/app/src/main/java/com/todo/app/common/exception/ResourceNotFoundException.java
  BE/app/src/main/java/com/todo/app/domain/column/controller/ColumnController.java
  BE/app/src/main/java/com/todo/app/domain/column/controller/response/CardResponse.java
  BE/app/src/main/java/com/todo/app/domain/column/controller/response/ColumnResponse.java
  BE/app/src/main/java/com/todo/app/domain/column/controller/response/Response.java
  BE/app/src/main/java/com/todo/app/domain/column/domain/Card.java
  BE/app/src/main/java/com/todo/app/domain/column/domain/Column.java
  BE/app/src/main/java/com/todo/app/domain/column/entity/CardEntity.java
  BE/app/src/main/java/com/todo/app/domain/column/entity/ColumnEntity.java
  BE/app/src/main/java/com/todo/app/domain/column/entity/Entity.java
  BE/app/src/main/java/com/todo/app/domain/column/repository/CardRepository.java
  BE/app/src/main/java/com/todo/app/domain/column/repository/CardRepositoryImpl.java
  BE/app/src/main/java/com/todo/app/domain/column/repository/ColumnRepository.java
  BE/app/src/main/java/com/todo/app/domain/column/repository/ColumnRepositoryImpl.java
  BE/app/src/main/java/com/todo/app/domain/column/repository/Repository.java
  BE/app/src/main/java/com/todo/app/domain/column/service/ColumnService.java
  BE/app/src/main/java/com/todo/app/domain/column/service/ColumnServiceImpl.java
  BE/app/src/main/java/com/todo/app/domain/column/service/Service.java
  BE/app/src/test/java/com/todo/app/domain/column/controller/ColumnControllerTest.java
Labels: ✨ feature

#20 [FE] Input reset css 추가
  fe/src/styles/GlobalStyles.ts
Labels: :art: style

#24 [FE] textarea reset css 추가
  fe/src/styles/GlobalStyles.ts
Labels: :art: style

#28 [FE] 메인 페이지 UI 구현
  fe/src/components/Button.tsx
  fe/src/components/ClosedIcon.tsx
  fe/src/components/EditIcon.tsx
  fe/src/components/PlusIcon.tsx
  fe/src/components/main/Card.tsx
Labels: ✨ feature

#29 [BE] History 저장, 조회 기능 추가
  BE/app/src/main/java/com/todo/app/AppApplication.java
  BE/app/src/main/java/com/todo/app/common/config/RedisConfig.java
  BE/app/src/main/java/com/todo/app/domain/column/controller/ColumnController.java
  BE/app/src/main/java/com/todo/app/domain/column/service/ColumnServiceImpl.java
  BE/app/src/main/java/com/todo/app/domain/history/controller/HistoryController.java
  BE/app/src/main/java/com/todo/app/domain/history/controller/response/HistoriesResponse.java
  BE/app/src/main/java/com/todo/app/domain/history/controller/response/HistoryResponse.java
  BE/app/src/main/java/com/todo/app/domain/history/entity/Action.java
  BE/app/src/main/java/com/todo/app/domain/history/entity/History.java
  BE/app/src/main/java/com/todo/app/domain/history/repository/HistoryRepository.java
  BE/app/src/main/java/com/todo/app/domain/history/repository/HistoryRepositoryImpl.java
  BE/app/src/main/java/com/todo/app/domain/history/repository/RedisCacheRepository.java
  BE/app/src/main/java/com/todo/app/domain/history/service/HistoryService.java
  BE/app/src/main/java/com/todo/app/domain/history/service/Service.java
Labels: ✨ feature

#27 [COMMON] README 페이지 양식 작성
  README.md
Labels: 📚 docs

#30 [FE] 로그인 페이지 구현
  fe/package-lock.json
  fe/package.json
  fe/src/App.tsx
  fe/src/components/UserInput.tsx
  fe/src/components/header/Navbar.tsx
  fe/src/pages/Login.tsx
  fe/src/pages/Main.tsx
  fe/src/pages/Sign.tsx
Labels: ✨ feature

#35 [FE] 로그인 페이지 UI 및 버튼 컴포넌트 구현
  fe/src/components/Button.tsx
  fe/src/pages/Main.tsx
  fe/src/pages/Sign.tsx
  fe/src/pages/SignUp.tsx
Labels: ✨ feature

#37 [FE] 메인 페이지 UI 구현
  fe/src/components/Button.tsx
Labels: ✨ feature

#39 [FE] 메인 페이지 UI 최종 구현
  fe/src/App.tsx
  fe/src/components/Badge.tsx
  fe/src/components/Button.tsx
  fe/src/components/HistoryIcon.tsx
  fe/src/components/PlusIcon.tsx
  fe/src/components/header/Header.tsx
  fe/src/components/header/Navbar.tsx
  fe/src/components/main/Card.tsx
  fe/src/components/main/Column.tsx
  fe/src/components/main/ColumnTitle.tsx
  fe/src/pages/Main.tsx
  fe/src/pages/Sign.tsx
  fe/src/styles/GlobalStyles.ts
Labels: ✨ feature

#40 [BE] 카드 이동 기능 추가
  BE/app/src/main/java/com/todo/app/common/ApiResponse.java
  BE/app/src/main/java/com/todo/app/domain/column/controller/CardController.java
  BE/app/src/main/java/com/todo/app/domain/column/controller/request/ActionRequestType.java
  BE/app/src/main/java/com/todo/app/domain/column/controller/request/CardMoveRequest.java
  BE/app/src/main/java/com/todo/app/domain/column/domain/Card.java
  BE/app/src/main/java/com/todo/app/domain/column/entity/CardEntity.java
  BE/app/src/main/java/com/todo/app/domain/column/entity/ColumnEntity.java
  BE/app/src/main/java/com/todo/app/domain/column/repository/CardRepository.java
  BE/app/src/main/java/com/todo/app/domain/column/repository/CardRepositoryImpl.java
  BE/app/src/main/java/com/todo/app/domain/column/repository/ColumnRepositoryImpl.java
  BE/app/src/main/java/com/todo/app/domain/column/service/CardService.java
  BE/app/src/main/java/com/todo/app/domain/column/service/CardServiceImpl.java
  BE/app/src/main/java/com/todo/app/domain/history/service/HistoryService.java
Labels: ✨ feature

#41 [BE] JWT 로그인 기능 추가 (미완성)
  BE/app/build.gradle
  BE/app/src/main/java/com/todo/app/common/aop/jwt/JwtAuthorizationFilter.java
  BE/app/src/main/java/com/todo/app/common/config/JwtConfig.java
  BE/app/src/main/java/com/todo/app/common/exception/GlobalExceptionHandler.java
  BE/app/src/main/java/com/todo/app/common/exception/IllegalJwtTokenException.java
  BE/app/src/main/java/com/todo/app/common/exception/IllegalPasswordException.java
  BE/app/src/main/java/com/todo/app/common/exception/JwtExceptionType.java
  BE/app/src/main/java/com/todo/app/domain/jwt/controller/JwtController.java
  BE/app/src/main/java/com/todo/app/domain/jwt/controller/request/JwtRefreshTokenRequest.java
  BE/app/src/main/java/com/todo/app/domain/jwt/controller/request/LoginRequest.java
  BE/app/src/main/java/com/todo/app/domain/jwt/controller/response/JwtExceptionResponse.java
  BE/app/src/main/java/com/todo/app/domain/jwt/controller/response/JwtResponse.java
  BE/app/src/main/java/com/todo/app/domain/jwt/controller/response/JwtTokenType.java
  BE/app/src/main/java/com/todo/app/domain/jwt/entity/Jwt.java
  BE/app/src/main/java/com/todo/app/domain/jwt/entity/JwtProvider.java
  BE/app/src/main/java/com/todo/app/domain/jwt/entity/Member.java
  BE/app/src/main/java/com/todo/app/domain/jwt/repository/JwtRepository.java
  BE/app/src/main/java/com/todo/app/domain/jwt/repository/JwtRepositoryImpl.java
  BE/app/src/main/java/com/todo/app/domain/jwt/service/JwtService.java
Labels: ✨ feature

#43 [BE] 카드 생성, 수정, 삭제 리펙토링 및 히스토리 추가
  BE/app/src/main/java/com/todo/app/domain/column/controller/CardController.java
  BE/app/src/main/java/com/todo/app/domain/column/controller/request/CardCreateRequest.java
  BE/app/src/main/java/com/todo/app/domain/column/controller/request/CardMoveRequest.java
  BE/app/src/main/java/com/todo/app/domain/column/controller/request/CardUpdateRequest.java
  BE/app/src/main/java/com/todo/app/domain/column/controller/response/CardResponse.java
  BE/app/src/main/java/com/todo/app/domain/column/domain/Card.java
  BE/app/src/main/java/com/todo/app/domain/column/domain/CardCreate.java
  BE/app/src/main/java/com/todo/app/domain/column/domain/CardUpdate.java
  BE/app/src/main/java/com/todo/app/domain/column/repository/CardRepository.java
  BE/app/src/main/java/com/todo/app/domain/column/repository/CardRepositoryImpl.java
  BE/app/src/main/java/com/todo/app/domain/column/service/CardService.java
  BE/app/src/main/java/com/todo/app/domain/column/service/CardServiceImpl.java
  BE/app/src/main/java/com/todo/app/domain/history/controller/HistoryController.java
  BE/app/src/main/java/com/todo/app/domain/history/repository/HistoryRepository.java
  BE/app/src/main/java/com/todo/app/domain/history/repository/HistoryRepositoryImpl.java
  BE/app/src/main/java/com/todo/app/domain/history/service/HistoryService.java
Labels: ♻️ refactor

#45 [FE] 카드 이동 기능 구현
  fe/src/components/Button.tsx
  fe/src/components/main/Card.tsx
  fe/src/components/main/Column.tsx
  fe/src/pages/Main.tsx
  fe/src/types/commons.d.ts
Labels: ✨ feature

#48 [BE] CORS 설정 및 기타 코드 수정
  BE/app/src/main/java/com/todo/app/common/config/WebConfig.java
  BE/app/src/main/java/com/todo/app/domain/column/controller/response/ColumnResponse.java
  BE/app/src/main/java/com/todo/app/domain/column/repository/CardRepositoryImpl.java
Labels: ✨ feature

#49 [FE] 로그인 기능 구현
  fe/src/main.tsx
  fe/src/pages/Sign.tsx
  fe/src/types/commons.d.ts
Labels: ✨ feature

#55 [BE] 회원 가입 기능 구현
  BE/app/src/main/java/com/todo/app/common/exception/GlobalExceptionHandler.java
  BE/app/src/main/java/com/todo/app/common/exception/MemberDuplicationException.java
  BE/app/src/main/java/com/todo/app/common/filter/JwtAuthorizationFilter.java
  BE/app/src/main/java/com/todo/app/domain/jwt/controller/JwtController.java
  BE/app/src/main/java/com/todo/app/domain/jwt/controller/request/SignInRequest.java
  BE/app/src/main/java/com/todo/app/domain/jwt/repository/JwtRepository.java
  BE/app/src/main/java/com/todo/app/domain/jwt/repository/JwtRepositoryImpl.java
  BE/app/src/main/java/com/todo/app/domain/jwt/service/JwtService.java
Labels: ✨ feature

#60 [BE] 활동기록 저장 로직에서 저장 DB를 Redis에서 MySQL로 수정
  BE/app/src/main/java/com/todo/app/domain/column/controller/CardController.java
  BE/app/src/main/java/com/todo/app/domain/column/service/ColumnServiceImpl.java
  BE/app/src/main/java/com/todo/app/domain/history/controller/HistoryController.java
  BE/app/src/main/java/com/todo/app/domain/history/repository/HistoryRepository.java
  BE/app/src/main/java/com/todo/app/domain/history/repository/HistoryRepositoryImpl.java
  BE/app/src/main/java/com/todo/app/domain/history/repository/RedisCacheRepository.java
  BE/app/src/main/java/com/todo/app/domain/history/service/HistoryService.java
Labels: 🥺 bug, ♻️ refactor

#62 [BE] Bug hot fix
  BE/app/src/main/java/com/todo/app/common/ApiResponse.java
  BE/app/src/main/java/com/todo/app/common/exception/GlobalExceptionHandler.java
  BE/app/src/main/java/com/todo/app/common/filter/JwtAuthorizationFilter.java
Labels: 🥺 bug

#64 [BE] 누락된 코드 추가
  BE/app/src/main/java/com/todo/app/domain/column/controller/CardController.java
  BE/app/src/main/java/com/todo/app/domain/column/controller/request/CardMoveRequest.java
  BE/app/src/main/java/com/todo/app/domain/history/repository/HistoryRepositoryImpl.java
Labels: ✨ feature

#70 [BE] 카드 수정 시 수정된 내용을 반환하도록 변경
  BE/app/src/main/java/com/todo/app/domain/column/controller/CardController.java
  BE/app/src/main/java/com/todo/app/domain/column/domain/Card.java
  BE/app/src/main/java/com/todo/app/domain/column/repository/CardRepository.java
  BE/app/src/main/java/com/todo/app/domain/column/repository/CardRepositoryImpl.java
  BE/app/src/main/java/com/todo/app/domain/column/service/CardService.java
  BE/app/src/main/java/com/todo/app/domain/column/service/CardServiceImpl.java
Labels: ✨ feature

#69 [BE] 카드 역순 정렬하여 반환하게 수정
  BE/app/src/main/java/com/todo/app/domain/column/repository/CardRepository.java
  BE/app/src/main/java/com/todo/app/domain/column/repository/CardRepositoryImpl.java
  BE/app/src/main/java/com/todo/app/domain/column/service/CardServiceImpl.java
Labels: ♻️ refactor

#65 [FE] 히스토리 기능 구현
  fe/src/components/ConfirmModal.tsx
  fe/src/components/header/Navbar.tsx
  fe/src/components/history/History.tsx
  fe/src/components/history/HistoryItem.tsx
  fe/src/components/history/HistoryList.tsx
  fe/src/pages/Main.tsx
  fe/src/pages/Sign.tsx
  fe/src/types/commons.d.ts
Labels: ✨ feature

#72 [FE] 카드 추가, 삭제, 편집 기능 구현
  fe/src/components/main/Card.tsx
  fe/src/components/main/CardContent.tsx
  fe/src/components/main/Column.tsx
  fe/src/components/main/ColumnTitle.tsx
  fe/src/pages/Main.tsx
  fe/src/types/commons.d.ts
  fe/src/useFetch.tsx
Labels: ✨ feature

#75 [BE] 필요없는 테스트 코드 제거
  BE/app/src/test/java/com/todo/app/domain/column/controller/ColumnControllerTest.java
Labels: 🥺 bug

#73 [BE] 로그인 로직 적용
  BE/app/src/main/java/com/todo/app/domain/column/controller/ColumnController.java
  BE/app/src/main/java/com/todo/app/domain/column/service/CardServiceImpl.java
  BE/app/src/main/java/com/todo/app/domain/column/service/ColumnServiceImpl.java
Labels: ✨ feature

#77 [BE] 배포 스크립트 작성
  BE/app/deploy.sh
Labels: ✨ feature, 🛠️ infra

#78 [BE] 카드 생성시 500에러 반환하는 버그 수정
  BE/app/src/main/java/com/todo/app/domain/column/domain/Card.java
  BE/app/src/main/java/com/todo/app/domain/column/repository/CardRepositoryImpl.java
Labels: 🥺 bug

#79 [BE] 히스토리 처음 불러올 때 가장 최근 히스토리를 불러오지 못하는 버그 수정
  BE/app/src/main/java/com/todo/app/domain/history/service/HistoryService.java
Labels: 🥺 bug

#81 📝docs: Update README.md
  README.md
Labels: 📚 docs

#83 📝docs: Update README.md
  README.md
Labels: 📚 docs
